// Code generated by easygin; DO NOT EDIT.

package middleware

import (

	"github.com/gin-gonic/gin"
)

func (r *MustAuth) EasyGinBindParameters(c *gin.Context) error {
	// 绑定头部参数 Authorization
	{
		headerVal := c.GetHeader("Authorization")
		if headerVal != "" {
			r.Authorization = string(headerVal)
		}
	}
	// 绑定查询参数 authorization
	{
		queryVal := c.Query("authorization")
		if queryVal != "" {
			r.AuthorizationInQuery = string(queryVal)
		}
	}
	return nil
}

