// Code generated by easygin; DO NOT EDIT.

package sub

import (
	"fmt"
	"strconv"

	"github.com/gin-gonic/gin"
)

func (r *ListSub) EasyGinBindParameters(c *gin.Context) error {
	// 绑定查询参数 size
	{
		queryVal := c.Query("size")
		if queryVal == "0" {
			queryVal = ""
		}
		if queryVal == "" {
			queryVal = "10"
		}
		if queryVal != "" {
			intVal, err := strconv.ParseInt(queryVal, 10, 64)
			if err != nil {
				return fmt.Errorf("invalid parameter 'size': %v", err.Error())
			}
			r.Size = int(intVal)
		}
	}
	// 绑定查询参数 offset
	{
		queryVal := c.Query("offset")
		if queryVal == "0" {
			queryVal = ""
		}
		if queryVal == "" {
			queryVal = "0"
		}
		if queryVal != "" {
			intVal, err := strconv.ParseInt(queryVal, 10, 64)
			if err != nil {
				return fmt.Errorf("invalid parameter 'offset': %v", err.Error())
			}
			r.Offset = int(intVal)
		}
	}
	return nil
}

